config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  devise_scope :user do
    get '/users', to: redirect("/users/sign_up")
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  get 'restaurants/top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'restaurants#top'
  get 'restaurants/search' => 'restaurants#search'
  resources :restaurants do
    resources :favorites, only: [:create, :destroy]
  end
  get 'users/profile' => 'users#show'
  resources :users, only: [:show] do
    get :favorites, on: :collection
  end
  resources :reviews, only: [:index, :create, :new, :destroy]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_restaurant
  before_action :authenticate_user!

  def create
    if @restaurant.registered_user_id != current_user.id
      @favorite = Favorite.create(user_id: current_user.id, restaurant_id: @restaurant.id)
    end
  end

  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, restaurant_id: @restaurant.id)
    @favorite.destroy
  end

  private
    def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if !Favorite.exists?(user_id: current_user.id, restaurant_id: restaurant.id) %>
<div class="favorite-btn-part">
  <%= link_to restaurant_favorites_path(restaurant.id), method: :post, remote: true, class:"favorite-btn" do %>
    <i class="far fa-star"></i>
  <% end %>
  <span class="star-count1">：<%= restaurant.favorites.count %></span>
</div>
<% else %>
<div class="favorite-btn-part">
  <%= link_to restaurant_favorite_path(restaurant_id: restaurant.id, id: restaurant.favorites[0].id), method: :delete, remote: true, class:"favorite-btn" do %>
    <i class="fas fa-star"></i>
  <% end %>
  <span class="star-count2">：<%= restaurant.favorites.count %></span>
</div>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_<%= @restaurant.id %>').html("<%= j(render partial: 'favorites/favorite', locals: { restaurant: @restaurant }) %>");

app/views/favorites/destroy.js.erb
$('#favorite_<%= @restaurant.id %>').html("<%= j(render partial: 'favorites/favorite', locals: { restaurant: @restaurant }) %>");