config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  devise_scope :user do
    get '/users', to: redirect("/users/sign_up")
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  get 'restaurants/top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'restaurants#top'
  get 'restaurants/search' => 'restaurants#search'
  resources :restaurants do
    resources :favorites, only: [:create, :destroy]
  end
  get 'users/profile' => 'users#show'
  resources :users, only: [:show] do
    get :favorites, on: :collection
  end
  resources :reviews, only: [:index, :create, :new, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, through: :restaurants
  has_many :favorites, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

  # パスワード変更機能
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords
    result
  end

  # ゲストユーザー
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64(10)
      user.password_confirmation = user.password
      user.user_name = 'ゲストユーザー'
      user.sex = 0
      user.age = 30
    end
  end

  # 性別値
  enum sex: { male: 0, female: 1 }

  # 画像アップロード
  mount_uploader :image, ImageUploader

  # 正規表現を定義
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)[a-z\d]+\z/i

  # バリデーション
  validates :user_name, presence: true
  validates :user_name, length: { maximum: 30 }, allow_blank: true
  validates :age, presence: true
  validates :age, numericality: true, allow_blank: true
  validates :email, presence: true
  validates :email, uniqueness: true, allow_blank: true
  validates :email, format: { with: VALID_EMAIL_REGEX }, allow_blank: true
  validates :password, presence: true, on: :create
  validates :password, length: { minimum: 6 }, allow_blank: true, on: :create
  validates :password, format: { with: VALID_PASSWORD_REGEX }, allow_blank: true, on: :create
  validates :password_confirmation, presence: true, on: :create
  validates :password_confirmation, length: { minimum: 6 }, allow_blank: true, on: :create
  validates :password_confirmation, format: { with: VALID_PASSWORD_REGEX }, allow_blank: true, on: :create
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :ensure_normal_user, only: %i[update destroy]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    users_profile_path
  end

  def after_update_path_for(resource)
    users_profile_path
  end

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません。'
    end
  end

  protected
    def update_resource(resource, params)
      resource.update_without_current_password(params)
    end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user.id)
    @restaurants = Restaurant.where(registered_user_id: @user.id)
    @reviews = Review.where(user_id: current_user.id)
    favorites = Favorite.where(user_id: current_user.id).order(created_at: :desc).pluck(:restaurant_id)
    @favorites = Restaurant.find(favorites)
  end

  private
    def user_params
      params.require(:user).permit(:image, :user_name, :age, :sex, :email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="container margin-top-20">
  <div class="col-sm-12 offset-md txt-center form-square border-bottom">
    <h3>プロフィール</h3>
    <br>
    <div id="tab">
      <div class="tab">
        <ul class="tab_title">
          <li @click="activate(1)" :class="{'active' : isActive === 1}">ユーザー情報</li>
          <li @click="activate(2)" :class="{'active' : isActive === 2}">お気に入り一覧</li>
          <li @click="activate(3)" :class="{'active' : isActive === 3}">投稿レビュー一覧</li>
          <li @click="activate(4)" :class="{'active' : isActive === 4}">投稿店舗一覧</li>
        </ul>
        <br>
        <ul class="tab_content">
          <li v-if="isActive === 1">
            <div class="row">
                <div class="col margin-bottom50">
                  <% if @user.image? %>
                    <%= image_tag @user.image.url, alt: "ユーザーアイコン", class: "profile-image d-block mx-auto" %>
                  <% else %>
                    <%= image_tag "default_icon.png", alt: "ユーザーアイコン", class: "profile-image d-block mx-auto" %>
                  <% end %>
                </div>
            </div>
            <br>
            <div class="row profile-margin">
              <div class="col profile-col">
                <label class="text-left mx-auto float-left">名前：</label>
                <span class="text-left mx-auto float-left"><%= @user.user_name %></span>
              </div>
            </div>
            <br>
            <div class="row profile-margin">
              <div class="col profile-col">
                <label class="text-left mx-auto float-left">年齢：</label>
                <span class="text-left mx-auto float-left"><%= @user.age %></span>
              </div>
            </div>
            <br>
            <div class="row profile-margin">
              <div class="col profile-col">
                <label class="text-left mx-auto float-left">性別：</label>
                <% if @user.male? %>
                  <span class="text-left mx-auto float-left">男性</span>
                <% else %>
                  <span class="text-left mx-auto float-left">女性</span>
                <% end %>
              </div>
            </div>
            <br>
            <div class="row profile-margin">
              <div class="col profile-col col-auto me-auto">
                <label class="text-left mx-auto float-left">メールアドレス：</label>
                <span class="text-left mx-auto float-left"><%= @user.email %></span>
              </div>
            </div>
            <br>
            <div class="martop-50 txt-center">
              <%= link_to "プロフィール編集", edit_user_registration_path, class: "btn btn-color width-25" %>
            </div>
          </li>
          <li v-else-if="isActive === 2">
            <% if @favorites.present? %>
              <table class="table table-striped v-align-mid">
                <thead>
                  <tr>
                    <th scope="col" class="col-mid"></th>
                    <th scope="col" class="col-mid">店舗名</th>
                    <th scope="col" class="col-mid">所在地</th>
                    <th scope="col" class="col-mid">お気に入り<br>登録日</th>
                    <th scope="col" class="col-mid"></th>
                  </tr>
                </thead>
                <tbody>
                  <% @favorites.each do |favorite| %>
                    <tr>
                      <th>
                        <% if favorite.restaurant_image? %>
                          <%= image_tag favorite.restaurant_image.url, class: "search-image mx-auto" %>
                        <% else %>
                          <img src="/assets/no_image.jpg" class="search-image mx-auto">
                        <% end %>
                      </th>
                        <td><%= favorite.restaurant_name %></td>
                        <td>〒<%= favorite.zipcode %>  <%= favorite.address %></td>
                        <td><%= favorite.created_at.strftime("%Y.%m.%d") %></td>
                        <td>
                          <%= link_to "店舗詳細", restaurant_path(favorite.id), class: "btn btn-color btn-sm" %>
                        </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            <% else %>
              <span class="font-weight-bold">お気に入り登録した店舗はありません</span>
            <% end %>
          </li>
          <li v-else-if="isActive === 3">
          <% if @reviews.present? %>
            <table class="table table-striped v-align-mid fixed">
              <thead>
                <tr>
                  <th scope="col">店舗名</th>
                  <th scope="col">評価</th>
                  <th scope="col">レビューコメント</th>
                  <th scope="col" class="user-detail-th"></th>
                </tr>
              </thead>
              <tbody>
                <% @reviews.each do |rv| %>
                  <tr>
                    <th class="post-rest-head"><%= rv.restaurant.restaurant_name %></th>
                    <td class="star-rate">
                      <span id="star-rate-<%= rv.id %>"></span>
                      <script>
                        $('#star-rate-<%= rv.id %>').raty({
                          size: 22,
                          starOff: "<%= asset_path('star-off.png') %>",
                          starOn: "<%= asset_path('star-on.png') %>",
                          starHalf: "<%= asset_path('star-half.png') %>",
                          half: true,
                          readOnly: true,
                          score: <%= rv.rate %>,
                        });
                      </script>
                      <span class="v-align-mid-span"><%= rv.rate %></span>
                    </td>
                    <td><%= rv.comment %></td>
                    <td>
                      <%= link_to "店舗詳細", restaurant_path(rv.restaurant_id), class: "btn btn-color btn-sm vertical-link margbot-5" %>
                      <%= link_to 'レビューを削除', review_path(rv.id), method: :delete, class: "btn btn-outline-danger btn-sm vertical-link", data: { confirm: "こちらのレビューを削除しますか？"} %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% else %>
            <p class="font-weight-bold">投稿したレビューはありません</p>
          <% end %>
          </li>
          <li v-else-if="isActive === 4">
          <% if @restaurants.present? %>
            <table class="table table-striped v-align-mid">
              <thead>
                <tr>
                  <th scope="col">店舗名</th>
                  <th scope="col">郵便番号</th>
                  <th scope="col">住所</th>
                  <th scope="col" class="user-post-detail-th"></th>
                </tr>
              </thead>
              <tbody>
                <% @restaurants.each do |r| %>
                  <tr>
                    <th class="text-center post-rest-head"><%= r.restaurant_name %></th>
                    <td class="text-center">〒<%= r.zipcode %></td>
                    <td class="text-center"><%= r.address %></td>
                    <td>
                      <%= link_to "詳細", restaurant_path(r.id), class: "btn btn-color btn-sm vertical-link margbot-5" %>
                      <%= link_to '削除', restaurant_path(r.id), method: :delete, class: "btn btn-outline-danger btn-sm vertical-link", data: { confirm: "投稿されたレビューを含めてこちらの店舗情報を削除します。本当によろしいですか？"} %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% else %>
            <p class="font-weight-bold">投稿した店舗はありません</p>
          <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>