config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  devise_scope :user do
    get '/users', to: redirect("/users/sign_up")
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  get 'restaurants/top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'restaurants#top'
  get 'restaurants/search' => 'restaurants#search'
  resources :restaurants do
    resources :favorites, only: [:create, :destroy]
  end
  get 'users/profile' => 'users#show'
  resources :users, only: [:show] do
    get :favorites, on: :collection
  end
  resources :reviews, only: [:index, :create, :new, :destroy]
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user, optional: true
  has_many :reviews, foreign_key: 'restaurant_id', dependent: :destroy
  has_many :favorites, dependent: :destroy

  # 店舗位置情報表示
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  # 正規表現
  VALID_POSTAL_CODE_REGEX = /\A\d{3}[-]?\d{4}\z/
  VALID_PHONE_REGEX = /\A0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1})[-)]?\d{4}\z|\A0[5789]0[-]?\d{4}[-]?\d{4}\z/

  # バリデーション
  validates :restaurant_name, presence: true
  validates :tel, presence: true
  validates :tel, format: { with: VALID_PHONE_REGEX }, allow_blank: true
  validates :zipcode, presence: true
  validates :zipcode, format: { with: VALID_POSTAL_CODE_REGEX }, allow_blank: true
  validates :address, presence: true

  # 店舗画像アップローダー
  mount_uploader :restaurant_image, RestaurantImageUploader
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # トップ画面遷移
  def top
  end

  # 店舗検索
  def search
    # エリアとキーワード両方入力された場合
    if params[:area].present? && params[:keyword].present?
      @restaurants = Restaurant.where('address LIKE(?) and restaurant_name LIKE(?) or address LIKE(?)', "%#{params[:area]}%", "%#{params[:keyword]}%", "%#{params[:keyword]}%")
      @recordcount = Restaurant.where('address LIKE(?) and restaurant_name LIKE(?) or address LIKE(?)', "%#{params[:area]}%", "%#{params[:keyword]}%", "%#{params[:keyword]}%").count
    # エリアのみが入力された場合
    elsif params[:area].present?
      @restaurants = Restaurant.where('address LIKE ?', "%#{params[:area]}%")
      @recordcount = Restaurant.where('address LIKE ?', "%#{params[:area]}%").count
    # キーワードのみが入力された場合
    elsif params[:keyword].present?
      @restaurants = Restaurant.where('restaurant_name LIKE(?) or address LIKE(?)', "%#{params[:keyword]}%", "%#{params[:keyword]}%")
      @recordcount = Restaurant.where('restaurant_name LIKE(?) or address LIKE(?)', "%#{params[:keyword]}%", "%#{params[:keyword]}%").count
    # 何も入力せずに検索した場合
    else
      @restaurants = Restaurant.all
      @recordcount = Restaurant.count
    end
  end

  # 店舗登録画面
  def new
    @restaurant = Restaurant.new
  end

  # 店舗登録処理
  def create
    @restaurant = Restaurant.new(restaurant_param)
    if @restaurant.save
      flash[:notice] = "店舗情報を登録しました"
      redirect_to restaurant_path(id: @restaurant)
    else
      render "new"
    end
  end

  # 店舗詳細
  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = Review.where(restaurant_id: @restaurant.id)
    if @reviews.blank?
      @average_rate = 0
    else
      @average_rate = @reviews.average(:rate).round(1)
    end
    @reviews_count = Review.where(restaurant_id: @restaurant.id).count
  end

  # 店舗情報編集
  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  # 店舗情報編集処理
  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_param)
      flash[:notice] = "店舗情報を編集しました"
      redirect_to restaurant_path(id: @restaurant)
    else
      render :edit
    end
  end

  # 削除処理
  def destroy
    restaurant = Restaurant.find(params[:id])
    if restaurant.registered_user_id == current_user.id
      restaurant.destroy
      flash[:notice] = "店舗情報の削除が完了しました"
      redirect_to root_path
    end
  end

  private
    # 店舗登録パラメータ
    def restaurant_param
      params.require(:restaurant).permit(:restaurant_name, :tel, :zipcode, :address, :restaurant_image, :registered_user_id, :latitude, :longitude)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/edit.html.erb
<div class="container margin-top-20">
  <div class="txt-center form-square page-label">
    <h3>店舗情報更新</h3>
    <%= render "shared/error", obj: @restaurant %>
    <%= form_with model: @restaurant, local: true do |r| %>
      <div class="field martop-30" id="img_field" @change="onFileChange($event)">
        <label class="restaurant-top-label">店舗画像</label>
        <div class="restaurant-img-parts">
          <% if @restaurant.restaurant_image? %>
            <img :src="imageData" v-if="imageData" class="restaurant-img d-block mx-auto">
            <img src=<%= @restaurant.restaurant_image.url %> v-else class="restaurant-img d-block mx-auto">
          <% else %>
            <img :src="imageData" v-if="imageData" class="restaurant-img d-block mx-auto">
            <img src="/assets/no_image.jpg" v-else class="restaurant-img d-block mx-auto">
          <% end %>
        </div>
        <%= r.file_field :restaurant_image, id: "file-input", accept: 'image/jpeg,image/gif,image/png', class: "mbｰ4", placeholder: "店舗画像をアップロード" %>
      </div>
      <div class="border-line pd-bottom30"></div>
      <div class="restaurant-info-parts martop-30">
        <div class="row">
          <%= r.label :restaurant_name, '店舗名', class: "col-md-3" %>
          <%= r.text_field :restaurant_name, class: "form-control mb-4 col-md-7" %>
        </div>
        <div class="row">
          <%= r.label :zipcode, '郵便番号', class: "col-md-3" %>
          <%= r.text_field :zipcode, class: "form-control mb-4 col-md-2" %>
        </div>
        <div class="row">
          <%= r.label :address, '所在地', class: "col-md-3" %>
          <%= r.text_field :address, class: "form-control mb-4 col-md-7" %>
        </div>
        <div class="row">
          <%= r.label :tel, '電話番号', class: "col-md-3" %>
          <%= r.text_field :tel, class: "form-control mb-md-5 col-md-3" %>
        </div>
        <%= r.hidden_field :registered_user_id, value: current_user.id %>
        <div class="row justify-content-center">
            <%= r.submit "更新", class: "btn btn-color btn-lg marginlg-5p width-15" %>
            <%= link_to "戻る", :back, class: "btn btn-outline-color btn-lg marginlg-5p width-15" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container margin-top-20">
  <div class="txt-center form-square page-label">
    <h3>店舗登録</h3>
    <%= render "shared/error", obj: @restaurant %>
    <%= form_with model: @restaurant, local: true do |r| %>
      <div class="field martop-30" id="img_field" @change="onFileChange($event)">
        <label class="restaurant-top-label">店舗画像</label>
        <div class="restaurant-img-parts">
          <img :src="imageData" v-if="imageData" class="restaurant-img d-block mx-auto">
          <img src="/assets/no_image.jpg" v-else class="restaurant-img d-block mx-auto">
        </div>
        <%= r.file_field :restaurant_image, id: "file-input", accept: 'image/jpeg,image/gif,image/png', class: "mbｰ4", placeholder: "店舗画像をアップロード" %>
      </div>
      <div class="border-line pd-bottom30"></div>
      <div class="restaurant-info-parts martop-30">
        <div class="row">
          <%= r.label :restaurant_name, '店舗名', class: "col-md-3" %>
          <%= r.text_field :restaurant_name, class: "form-control mb-4 col-md-7" %>
        </div>
        <div class="row">
          <%= r.label :zipcode, '郵便番号', class: "col-md-3" %>
          <%= r.text_field :zipcode, class: "form-control mb-4 col-md-2" %>
        </div>
        <div class="row">
          <%= r.label :address, '所在地', class: "col-md-3" %>
          <%= r.text_field :address, class: "form-control mb-4 col-md-7" %>
        </div>
        <div class="row">
          <%= r.label :tel, '電話番号', class: "col-md-3" %>
          <%= r.text_field :tel, class: "form-control mb-md-5 col-md-3" %>
        </div>
        <%= r.hidden_field :registered_user_id, value: current_user.id %>
        <div class="row justify-content-center">
            <%= r.submit "登録", class: "btn btn-color btn-lg marginlg-5p width-15" %>
            <%= link_to "戻る", :back, class: "btn btn-outline-color btn-lg marginlg-5p width-15" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/search.html.erb
<div class="container margin-top-20">
  <div class="txt-center form-square-search page-label">
    <div class="search-result">
      <p>検索結果：<%= @recordcount %>件</p>
      <% if @recordcount == 0 %>
        <p class="text-center">該当するお店が見つかりませんでした。</p>
        <p class="text-center">検索条件をご確認の上、再度お試しください。</p>
      <% end %>
    </div>
    <table class="table fixed">
      <thead>
        <tr>
          <th scope="col"></th>
          <th scope="col">店舗名</th>
          <th scope="col">所在地</th>
          <th scope="col" class="search-detail-th"></th>
        </tr>
      </thead>
      <tbody>
        <% @restaurants.each do |r| %>
          <tr>
            <% if r.restaurant_image? %>
              <th class="text-left"><%= image_tag r.restaurant_image.url, class: "search-image" %></th>
            <% else %>
              <th class="text-left"><%= image_tag "/assets/no_image.jpg", class: "search-image" %></th>
            <% end %>
            <td class="text-left"><%= r.restaurant_name %></td>
            <td class="text-left">〒<%= r.zipcode %>  <%= r.address %></td>
            <td><%= link_to "詳細", restaurant_path(r.id), class: "btn btn-color btn-sm", id: "detail-button" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/restaurants/show.html.erb
<script type="text/javascript">
  function initMap() {
    var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15, 
              center: {lat: <%= @restaurant.latitude %>, lng: <%= @restaurant.longitude %>}
              });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);
    var contentString = '住所：<%= @restaurant.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });
    var marker = new google.maps.Marker({
                  position: {lat: <%= @restaurant.latitude %>, lng: <%= @restaurant.longitude %>},
                  map: map,
                  title: contentString
                 });
     marker.addListener('click', function() {
       infowindow.open(map, marker);
     });
  }
</script>
<%= render partial: 'layouts/notifications' %>
<div class="container margin-top-20">
  <div class="txt-center form-square page-label">
    <h3>店舗詳細</h3>
    <h4 class="restaurant-name-title"><%= @restaurant.restaurant_name %></h4>
    <% if user_signed_in? %>
      <% if @restaurant.registered_user_id != current_user.id %>
        <div class='star-btn text-right' id="favorite_<%= @restaurant.id %>">
          <%= render "favorites/favorite", restaurant: @restaurant %>
        </div>
      <% end %>
    <% end %>
    <div class="field martop-15" id="img_field" @change="onFileChange($event)">
      <div class="restaurant-img-parts">
        <% if @restaurant.restaurant_image? %>
          <%= image_tag @restaurant.restaurant_image.url, class: "restaurant-img d-block mx-auto" %>
        <% else %>
          <img src="/assets/no_image.jpg" class="restaurant-img d-block mx-auto">
        <% end %>
      </div>
    </div>
    <div class="border-line pd-bottom30"></div>
    <br>
    <ul class="tab-list list-unstyled">
      <li class="tab-restaurant tab-active">基本情報</li>
      <li class="tab-restaurant">地図</li>
      <li class="tab-restaurant">評価・レビュー</li>
    </ul>
    <br>
    <div class="tabbox-contents">
      <div class="tabbox box-show">
        <section>
          <div class="restaurant-detail-info text-left">
            <h2 class="detail-info-text"><%= @restaurant.restaurant_name %> 基本情報</h2>
            <div class="info-inner">
            <% if user_signed_in? %>
              <% if @restaurant.registered_user_id == current_user.id %>
              <div class="info-table margbot-30">
              <% else %>
              <div class="info-table margbot-10">
              <% end %>
            <% else %>
              <div class="info-table margbot-10">
            <% end %>
                <table class="basic-table">
                  <tbody>
                    <tr>
                      <th>店舗名</th>
                      <td>
                        <p id="info-name"><%= @restaurant.restaurant_name %></p>
                      </td>
                    </tr>
                    <tr>
                      <th>電話番号</th>
                      <td>
                        <p><%= @restaurant.tel %></p>
                      </td>
                    </tr>
                    <tr>
                      <th>住所</th>
                      <td>
                        <p>〒<%= @restaurant.zipcode %> <%= @restaurant.address %></p>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <div class="row justify-content-center">
              <% if user_signed_in? %>
                <% if @restaurant.registered_user_id == current_user.id %>
                  <%= link_to "編集", edit_restaurant_path(@restaurant.id), class: "btn btn-color btn-sm marginlg-2p" %>
                  <%= link_to '店舗を削除する', restaurant_path(@restaurant.id), method: :delete, class: "btn btn-outline-danger btn-sm marginlg-2p", data: { confirm: "投稿されたレビューを含めてこちらの店舗情報を削除します。本当によろしいですか？"} %>
                <% end %>
              <% end %>
              </div>
            </div>
          </div>
        </section>
      </div>
      <div class="tabbox">
        <section>
          <div class="restaurant-detail-info text-left">
            <h2 class="detail-info-text"><%= @restaurant.restaurant_name %> 所在地</h2>
            <div class="info-inner">
              <div class="info-table">
                <div id="map"></div>
              </div>
            </div>
          </div>
        </section>
      </div>
      <div class="tabbox">
        <% if @reviews.present? %>
          <p class="customer-rate-label margbot-10">カスタマーレビュー</p>
          <div class="average-review-rating" data-score=<%= @average_rate %>></div>
          <script type="application/javascript">
            $('.average-review-rating').raty({
              readOnly: true,
              path: '/assets/',
              score: function() {
                return $(this).attr('data-score')
              }
            });
          </script>
          <p class="customer-rate-label margbot-5"><%= @average_rate %></p>
          <p><%= @reviews_count %>件のレビュー</p>
          <table class="table table-striped v-align-mid fixed">
            <thead>
              <tr>
                <th scope="col">ユーザー名</th>
                <th scope="col">評価</th>
                <th scope="col" class="commnet-th">レビューコメント</th>
              </tr>
            </thead>
            <tbody>
              <% @reviews.each do |rv| %>
                <tr>
                  <th>
                  <% if rv.user.image? %>
                    <%= image_tag rv.user.image.url, alt: "ヘッダーアイコン", class: "mxｰ3 p-1 host-icon" %>
                  <% else %>
                    <img src="/assets/default_icon.png" class="mxｰ3 p-1 host-icon" alt="ヘッダーアイコン">
                  <% end %>
                  <span><%= rv.user.user_name %></span>
                  </th>
                  <td>
                    <span id="star-rate-<%= rv.id %>"></span>
                    <script type="application/javascript">
                      $('#star-rate-<%= rv.id %>').raty({
                        size: 24,
                        starOff: "<%= asset_path('star-off.png') %>",
                        starOn: "<%= asset_path('star-on.png') %>",
                        starHalf: "<%= asset_path('star-half.png') %>",
                        half: true,
                        readOnly: true,
                        score: <%= rv.rate %>,
                      });
                    </script>
                    <span class="rate-score"><%= rv.rate %></span>
                  </td>
                  <td><%= rv.comment %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <% if user_signed_in? %>
            <%= link_to "レビュー投稿する", new_review_path(id: @restaurant.id), class: "btn btn-color marginlg-2p" %>
          <% else %>
            <a class="link-inactive btn btn-color marginlg-2p">レビュー投稿する</a>
            <p class="reminder-text martop-15">レビュー投稿は会員のみご利用できます。</p>
            <p class="reminder-text">会員登録は<%= link_to "こちら", new_user_registration_path, class: "reminder-link" %></p>
          <% end %>
        <% else %>
          <p class="font-weight-bold margbot-30">こちらの店舗のレビューはありません</p>
          <% if user_signed_in? %>
            <%= link_to "レビュー投稿する", new_review_path(id: @restaurant.id), class: "btn btn-color marginlg-2p" %>
          <% else %>
            <a class="link-inactive btn btn-color marginlg-2p">レビュー投稿する</a>
            <p class="reminder-text martop-15">レビュー投稿は会員のみご利用できます。</p>
            <p class="reminder-text">会員登録は<%= link_to "こちら", new_user_registration_path, class: "reminder-link" %></p>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="row justify-content-center">
      <%= link_to "戻る", :back, class: "btn btn-outline-color marginlg-5p width-15" %>
    </div>
  </div>
</div>
<script async defer
  src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API'] %>&callback=initMap">
</script>

app/views/restaurants/top.html.erb
<%= render partial: 'layouts/notifications' %>
<div class="main-visual">
  <h5>テイクアウトショップ共有サイト</h5>
  <%= image_tag 'topmain_logo.png', :class=>"img-fluid", :alt => 'トップ画面のメインロゴ' %>
  <h6>エリア・キーワードからテイクアウトのお店を探してみましょう。</h6>
<%= form_with url: restaurants_search_path, class: 'form-inline', method: :get, local: true do |r| %>
  <div class="row mx-auto">
    <div class="col pd-right0 input-group-lg">
      <%= r.text_field :area, placeholder: "エリア", class: "form-control", id: "large-area" %>
    </div>
    <div class="col pd-left0 pd-right0 input-group-lg">
      <%= r.text_field :keyword, placeholder: "キーワード", class: "form-control", id: "large-keyword" %>
    </div>
    <%= submit_tag '検索', class: "btn btn-color btn-lg", id: "large-search" %>
  </div>
<% end %>
</div>
<div class="container">
  <div class="container-square square-parts">
    <h4>「フジノキ」とは？</h4>
    <br>
     <div class="row mx-auto margbot-30">
      <div class="col">
        <%= image_tag 'food_takeout_woman.png', :class=>"square-parts-img img-fluid d-block mx-auto", :alt => 'テイクアウトイラスト' %>
      </div>
    </div>
    <p>
      昨今新型コロナウイルスが蔓延する中、人との接触を控えるようになりました。
      <br>
      そのため、外食よりテイクアウトによる食事の需要が高まっております。
      <br>
      「フジノキ」ではテイクアウトが可能のお店がどこにあるのか、
      <br>
      そのお店の評判はどういったものか等といった方に向けて、共有頂けるよう、
      <br>
      こちらのサイトを作成致しました。
    </p>
  </div>
</div>
<div class="container">
  <div class="container-square square-parts">
    <h4>会員登録を行うと？</h4>
    <br>
    <div class="row mx-auto margbot-30">
      <div class="col">
        <%= image_tag 'review_man_star5.png', :class=>"square-parts-img img-fluid d-block float-right", :alt => '星5男性イラスト' %>
      </div>
      <div class="col">
        <%= image_tag 'review_woman_star5.png', :class=>"square-parts-img img-fluid d-block float-left", :alt => '星5女性イラスト' %>
      </div>
    </div>
    <p>
      会員登録を行うと店舗検索の他、店舗の登録やレビューの投稿といった機能がご利用できます。
      <br>
      是非会員登録して頂き、店舗の情報やレビューを他の方に共有してみましょう!
      <br>
    </p>
    <% unless user_signed_in? %>
    <div class="martop-30 txt-center">
      <%= link_to "今すぐ登録", new_user_registration_path, class: "btn btn-color btn-lg" %>
    </div>
    <% end %>
  </div>
</div>